### ISSUE TITLE
模拟器和Native下没效果

### ISSUE THREAD

**Issue by caogtaa** [BlubluBlue7/Page#1]
模拟器和Native下没效果，我已经兼容了，请问接受PR吗？

**Comment by BlubluBlue7** [comment]
> 模拟器和Native下没效果，我已经兼容了，请问接受PR吗？

可以的，十分感谢

**Comment by caogtaa** [comment]
抱歉，刚发现is_front忘记写入顶点数据了，测试效果的时候没注意正面反面，我等下再PR下。
